[build]
  command = "yarn build"
  functions = "api/dist"
  publish = "web/dist"

[context.production]
  environment = { YARN_VERSION = "1.12.1", HAMMER_ENV = "production" }

[context.deploy-preview]
  environment = { YARN_VERSION = "1.12.1", HAMMER_ENV = "production" }